config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :subscriptions
  resources :products
  resources :addresses
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :address
  has_many :payments, dependent: :destroy
  accepts_nested_attributes_for :payments

  enum frequency: [:weekly, :biweekly, :monthly]
  enum status: [:active, :paused, :cancelled, :pending_payment]
  after_initialize :set_default_frequency, :if => :new_record?
  after_initialize :set_default_status, :if => :new_record?

  def set_default_frequency
    self.frequency ||= :biweekly
  end

  def set_default_status
    self.status ||= :pending_payment
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
    @addresses = current_user.addresses
    @products = Product.all
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    p "in subs controller create"
    @subscription = Subscription.new(subscription_params)


    @amount = 500
    @payment = Payment.new(amount: @amount, token: params[:payment][:token])
    customer = find_customer
    begin
      charge = Stripe::Charge.create({
                                         customer: customer.id,
                                         amount: @amount,
                                         description: 'Rails Stripe customer',
                                         currency: 'usd',
                                     })
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_subscription_path
    end


    @subscription.next_delivery = DateTime.now.to_date
    @subscription.prev_delivery = DateTime.now.to_date
    @subscription.user = current_user


    respond_to do |format|
      if @subscription.save
        @payment.subscription = @subscription
        @payment.save
        p "after save #{@payment}"
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      # params.fetch(:subscription, {})
      params.require(:subscription).permit(:frequency, :product_id, :address_id, :token)
    end

    def find_customer
      if current_user.stripe_token
        retrieve_customer(current_user.stripe_token)
      else
        create_customer
      end
    end

    def retrieve_customer(stripe_token)
      Stripe::Customer.retrieve(stripe_token)
    end

    def create_customer
      customer = Stripe::Customer.create(
          email: current_user.email,
          source: params[:payment][:token]
      )
      # customer.sources.create({source: params[:token]})
      current_user.update(stripe_token: customer.id)
      customer
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<script language="JavaScript">
    Stripe.setPublishableKey("<%= ENV['STRIPE_TEST_PUBLISHABLE_KEY'] %>");
</script>
<%= form_for subscription, :html => { :class => "cc_form" }  do |f| %>
  <% if subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
        <% subscription.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row col-md-12">
    <%= f.label :frequency %>
    <%= f.select(:frequency, Subscription.frequencies.keys.map {|frequency| [frequency.titleize,frequency]}, {}, { :class => 'form-control' }) %>
  </div>


  <div class="row col-md-6">
    <%= f.label :product %>
    <%= f.collection_select :product_id, @products, :id, :name, {}, {:class => 'form-control'} %>
  </div>

  <%= fields_for( :product ) do |p| %>
    <div class="row col-md-6">
      <%= p.label :size %>
      <%= p.select(:size, Product.sizes.keys.map {|size| [size.titleize,size]}, {}, { :class => 'form-control' }) %>
    </div>
  <% end %>


  <div class="row col-md-12">
    <%= f.label :address %>
    <%= f.collection_select :address_id, @addresses, :id, :address1, {}, {:class => 'form-control'} %>
  </div>

  <%= fields_for( :payment ) do |p| %>
    <div class="row col-md-12">
      <div class="form-group col-md-4">
        <%= p.label :card_number, "Card Number", data: { stripe: 'label'} %>
        <%= p.text_field :card_number, class: "form-control", required: true, data: { stripe: 'number'} %>
      </div>
      <div class="form-group col-md-2">
        <%= p.label :card_cvv, "Card CVV", data: { stripe: 'label'} %>
        <%= p.text_field :card_cvv, class: "form-control", required: true, data: { stripe: 'cvv'} %>
      </div>
      <div class="form-group col-md-6">
        <div class="col-md-12">
          <%= p.label :card_expires, "Card Expires", data: { stripe: 'label'} %>
        </div>
        <div class="col-md-3">
          <%= p.select :card_expires_month, options_for_select(Payment.month_options),
                       { include_blank: 'Month' },
                       "data-stripe" => "exp-month",
                       class: "form-control", required: true %>
        </div>
        <div class="col-md-3">
          <%= p.select :card_expires_year, options_for_select(Payment.year_options.push),
                       { include_blank: 'Year' },
                       class: "form-control",
                       data: { stripe: "exp-year" }, required: true %>
        </div>
      </div>
    </div>
  <% end %>


  <%= f.button :submit, :class => 'btn btn-primary' %>

<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subscriptions</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Frequency</th>
    <th>Product</th>
    <th>Next Delivery</th>
    <th>Status</th>
    <th>Address</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% @subscriptions.each do |subscription| %>
    <% address = subscription.address %>
    <tr>
      <td><%= subscription.frequency %></td>
      <td><%= "#{subscription.product.name} #{subscription.product.size}" %></td>
      <td><%= subscription.next_delivery %></td>
      <td><%= subscription.status %></td>
      <td><%= "#{address.address1} #{address.address2} #{address.city} #{address.zip_code}"  %></td>
      <td><%= link_to 'Show', subscription %></td>
      <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
      <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>