config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :subscriptions
  resources :products
  resources :addresses
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    # @addresses = Address.all
    @addresses = current_user.addresses
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)
    # p ENV["SMARTY_STREETS_AUTH_ID"]
    # p ENV["SMARTY_STREETS_AUTH_TOKEN"]
    # verifier = MainStreet::AddressVerifier.new("#{@address.address1} #{@address.address2}, #{@address.city}, CA #{@address.zip_code}")
    # p verifier
    @address.user = current_user



    respond_to do |format|
      # if verifier.success? and @address.save
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      # params.fetch(:address, {})
      params.require(:address).permit(:address1, :address2, :city, :zip_code)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.erb
<%#= form_with(model: address, local: true) do |form| %>


<!--  <div class="actions">-->
    <%#= form.submit %>
<!--  </div>-->
<%# end %>


<%= form_for address do |f| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
        <% address.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :address1 %>
  <%= f.text_field :address1 %>

  <%= f.label :address2 %>
  <%= f.text_field :address2 %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :zip_code %>
  <%= f.text_field :zip_code %>

  <%= f.button :submit %>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Delivery Addresses</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Street</th>
    <th>Apt/Suite</th>
    <th>City</th>
    <th>Zip</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% @addresses.each do |address| %>
    <tr>
      <td><%= address.address1 %></td>
      <td><%= address.address2 %></td>
      <td><%= address.city %></td>
      <td><%= address.zip_code %></td>
      <td><%= link_to 'Show', address %></td>
      <td><%= link_to 'Edit', edit_address_path(address) %></td>
      <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Address1</th>
    <th>Address2</th>
    <th>City</th>
    <th>Zip</th>
  </tr>
  </thead>
  <tbody>
  <% @addresses.each do |address| %>
    <tr>
      <td><%= address.address1 %></td>
      <td><%= address.address2 %></td>
      <td><%= address.city %></td>
      <td><%= address.zip_code %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>